### ISSUE TITLE
Useless code

### ISSUE THREAD

**Issue by Pana** [moll/js-co-next#1]
``` JavaScript
if (fn.length == 4) return function(err, req, res, next) {
    return co(fn.call(this, err, req, res, next)).catch(next)
}
```

I think this code is useless, because it is equal with rear code 

```
return function() {
      return co(fn.apply(this, arguments)).catch(arguments[arguments.length - 1])
}
```

**Comment by moll** [comment]
Hey! Functionally, indeed, you're right, but Express does a bit of dynamic type overloading and checks the arity of a function (the number of args it takes). I think I added a comment above the offending line too. :-)

**Comment by Pana** [comment]
Thanks explain

**Comment by moll** [comment]
You're welcome. I'll close this, but feel free to carry on chatting. :)
